language: dart

dart:
  - dev

sudo: required
addons:
  chrome: stable

jobs:
  include:
    - stage: analyze_and_format
      script:
        - dartanalyzer --fatal-warnings .
        - dartfmt -n --set-exit-if-changed .
    - stage: test
      script:
        - pub run test -p vm
        - pub run test -p chrome
    - stage: coverage
      script:
        - pub run coverage:collect_coverage --port=8111 -o coverage.json \
          --resume-isolates --wait-paused &
        - dart --observe=8111 test/*
        - pub run coverage:format_coverage --packages=.packages \
          --report-on=lib --in coverage.json --out lcov.info --lcov
        - bash <(curl -s https://codecov.io/bash)

stages:
  - analyze_and_format
  - test
  - coverage

cache:
  directories:
    - $HOME/.pub-cache
