language: dart

dart:
  - dev

sudo: required
addons:
  chrome: stable

jobs:
  include:
    - stage: analyze_and_format
      script:
        - dartanalyzer --fatal-warnings .
        - dartfmt -n --set-exit-if-changed .
    - stage: test
      script:
        - pub run test -p vm
        - pub run test -p chrome
    - stage: coverage
      script:
        - OBS_PORT=9292
        - dart \
          --enable-vm-service=${OBS_PORT} \
          --pause-isolates-on-exit \
          test/* &
        - pub run coverage:collect_coverage \
          --port=${OBS_PORT}  \
          --out=coverage.json \
          --resume-isolates   \
          --wait-paused
        - pub run coverage:format_coverage \
          --packages=.packages \
          --report-on=lib      \
          --in=coverage.json   \
          --out=lcov.info      \
          --lcov
        - bash <(curl -s https://codecov.io/bash)

stages:
  - analyze_and_format
  - test
  - coverage

cache:
  directories:
    - $HOME/.pub-cache
