language: dart

dart:
  - dev

dart_task:
  - test: --platform vm
  - test: --platform chrome
  - dartanalyzer
  - dartfmt

script:
  - set -e
  - pub run coverage:collect_coverage --port=8111 -o coverage.json --resume-isolates --wait-paused &
  - dart --observe=8111 test/*
  - pub run coverage:format_coverage --packages=.packages --report-on=lib --in coverage.json --out lcov.info --lcov
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.pub-cache
