name: q_calc_util
description: >
  Dixon's Q Test calculator package for Dart. It makes it easy to identify an
  outlier in a range between 3 and 30 double numbers
version: 0.1.2
homepage: https://github.com/ChemisTechlabs/q_calc_util
author: Guilherme Caldas <gcaldas@chemis.org>

environment:
  sdk: '>=2.0.0 <3.0.0'

dev_dependencies:
  test: ^1.9.4
  test_coverage: ^0.4.0
  pedantic: ^1.0.0
