name: q_calc_util
description: >
  Dixon's Q Test calculator package for Dart. It makes it easy to identify an 
  outlier in a range between 3 and 30 double numbers
version: 0.1.1
homepage: https://github.com/ChemisTechlabs/q_calc_util
author: Guilherme Caldas <gui.caldas.o@gmail.com>

environment:
  sdk: ">=2.0.0 <3.0.0"

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
  coverage: ^0.12.3
