name: q_calc_util
description: Dixon's Q Test calculator package for Dart
version: 0.1.0
homepage: https://github.com/ChemisTechlabs/q_calc_util
author: Guilherme Caldas <gui.caldas.o@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  test: ^1.0.0
